/*
 * modificarDatosSupermercado.h
 *
 *  Created on: 5 abr 2026
 *      Author: mike
 */

#ifndef MENUADMIN_MENUGESTSUPERMERCADO_MODIFICARDATOSSUPERMERCADO_H_
#define MENUADMIN_MENUGESTSUPERMERCADO_MODIFICARDATOSSUPERMERCADO_H_

void modificarStockSupermercado();

#endif /* MENUADMIN_MENUGESTSUPERMERCADO_MODIFICARDATOSSUPERMERCADO_H_ */
